sudo: false
language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - sys-img-armeabi-v7a-android-23

licenses:
  - 'android-sdk-license-.+'

before_install:
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

before_script:
   - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 128M
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82

script:
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)
