sudo: false
language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2

licenses:
  - 'android-sdk-license-.+'

script:
  - ./gradlew :library:check

after_success:
  - bash <(curl -s https://codecov.io/bash)
