sudo: false
language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - sys-img-armeabi-v7a-android-23

licenses:
  - 'android-sdk-license-.+'

before_install:
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

script:
  - ./gradlew jacocoTestReportDebug

after_success:
  - bash <(curl -s https://codecov.io/bash)
